version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      AGENT_PORT: "8000"
