import { FunctionTool } from "@google/adk";
import type {
  GenerateVideosConfig,
  GenerateVideosParameters,
} from "@google/genai";
import { z } from "zod";

import { createGenAIClient } from "@/veo/client";
import { generateVideo } from "@/veo/generateVideo";

export const generateVideoTool = new FunctionTool({
  name: "generate_video",
  description:
    "Generate a short video using Veo from a prompt and return the generated bytes.",
  isLongRunning: true,
  parameters: z.object({
    prompt: z.string().min(1),
    seed: z.number().int(),

    durationSeconds: z.number().int().min(1).max(120).default(8),
    aspectRatio: z.string().optional().default("19:6"),
    enhancePrompt: z.boolean().optional().default(true),
    generateAudio: z.boolean().optional(),
  }),
  execute: async (input, toolContext) => {
    const ai = createGenAIClient();
    const bucket = process.env.GOOGLE_CLOUD_BUCKET;
    const sessionId = toolContext?.sessionId ?? "unknown_session";
    const outputGcsUri = `gs://${bucket}/${sessionId}/${input.seed}`;

    const params: GenerateVideosParameters = {
      prompt: input.prompt,
      model: "veo-3.1-generate-preview",
      config: {
        outputGcsUri: outputGcsUri,
        durationSeconds: input.durationSeconds,
        seed: input.seed,
        aspectRatio: input.aspectRatio,
        personGeneration: "allow_adult",
        enhancePrompt: input.enhancePrompt,
        generateAudio: input.generateAudio,
      } as GenerateVideosConfig,
    };

    return await generateVideo(ai, params);
  },
});
