name: Deploy to GCP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      TF_VAR_project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Apply Deployment
        run: |
          gcloud infra-manager deployments apply glac-deployment \
          --location=us-central1 \
          --local-source=infra \
